export const AFFILIATION_LIST = [
  { value: '', label: '선택' },
  { value: 'AI융합대학', label: 'AI융합대학' },
  { value: '간호대학(1학년)', label: '간호대학(1학년)' },
  { value: '경영대학', label: '경영대학' },
  { value: '공과대학', label: '공과대학' },
  { value: '농업생명과학대학', label: '농업생명과학대학' },
  { value: '본부직할학부', label: '본부직할학부' },
  { value: '사범대학', label: '사범대학' },
  { value: '사회과학대학', label: '사회과학대학' },
  { value: '생활과학대학', label: '생활과학대학' },
  { value: '수의과대학', label: '수의과대학' },
  { value: '약학대학', label: '약학대학' },
  { value: '예술대학', label: '예술대학' },
  { value: '의과대학(1학년)', label: '의과대학(1학년)' },
  { value: '인문대학', label: '인문대학' },
  { value: '자연과학대학', label: '자연과학대학' },
  { value: '치과대학', label: '치과대학' },
];
