name: React App CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Node.js ${{ matrix.node-version }} 사용
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: pnpm 설치
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: pnpm store 경로 설정
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: pnpm cache 설정
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: dependencies 설치
        run: pnpm install --lockfile

      - name: env 파일 생성
        run: |
          touch .env
          echo VITE_PUBLIC_API_URL=${{ secrets.VITE_PUBLIC_API_URL }} >> .env
          cat .env

      - name: 프로젝트 pnpm 빌드
        run: |
          pnpm build:apply
          pnpm build:manager

      - name: service-apply 모듈 배포
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_APPLY_WS_BUCKET_NAME }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            SOURCE_DIR: "dist/service-apply"

      - name: service-manager 모듈 배포
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_MANAGER_WS_BUCKET_NAME }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            SOURCE_DIR: "dist/service-manager"