name: Dev Deploy CI/CD
on:
  push:
    branches:
      - feat/dev-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Node.js ${{ matrix.node-version }} 사용
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies, --ignore-scripts]
            - args: [--global, gulp, prettier, typescript]

      - name: env 파일 생성
        run: |
          touch .env
          echo VITE_PUBLIC_API_URL=${{ secrets.VITE_PUBLIC_API_URL }} >> .env
          cat .env

      - name: 프로젝트 pnpm 빌드
        run: |
          pnpm build:apply
          pnpm build:manager

      - name: service-apply 모듈 배포
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.DEV_AWS_DEFAULT_REGION }}
        run: |
          aws s3 sync dist/service-apply s3://${{ secrets.DEV_AWS_APPLY_WS_BUCKET_NAME }}

      - name: service-manager 모듈 배포
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.DEV_AWS_DEFAULT_REGION }}
          SOURCE_DIR: "dist/service-manager"
        run: |
          aws s3 sync dist/service-manager s3://${{ secrets.DEV_AWS_MANAGER_WS_BUCKET_NAME }}
